### ISSUE TITLE
Inquiry: Installation of Google Play Services on Autel EVO II Pro V3 Drone's Remote Controller

### ISSUE THREAD

**Issue by tuannguyenneo** [AutelSDK/AndroidAdvanceSample#12]
**Issue Description:**
I am interested in installing Google Play Services on the Remote Controller of the Autel EVO II Pro V3 drone. 
Currently, the Remote Controller does not have Google Play Services pre-installed. 
My intention is to utilize Google Maps functionality. I would like to inquire about the feasibility of installing Google Play Services on the Remote Controller and request guidance on the specific installation process.

**Questions:**

1. Is it possible to install Google Play Services on the Remote Controller of the Autel EVO II Pro V3 drone?
2. If installation is feasible, could you please provide detailed instructions or guidelines for installing Google Play Services on the Remote Controller?
3. Are there any potential limitations, compatibility issues, or prerequisites that I should be aware of before attempting to install Google Play Services?

**Additional Information:**
Autel EVO II Pro V3 drone model
Objective: Installation of Google Play Services on the Remote Controller
Purpose: Google Maps functionality

I appreciate any assistance or information you can provide regarding this matter. 
Thank you for your support.

**Comment by masayuki-kobayashi1** [comment]
Additional Question
Is it possible to provide an OS/Firmware with Google Play Services pre-installed?

**Comment by tuannguyenneo** [comment]
It's impossible.
