### ISSUE TITLE
the demo app keeps stopping

### ISSUE THREAD

**Issue by planewave** [AutelSDK/AndroidAdvanceSample#2]
Hi there

I have installed this demo app on two Android phones and even the RC tablet. however, it always shows `unknown` on top of the app, and if click any button in the secondary menu, this demo app crashes or reboots. 

I think I have a connection problem (is it?). According to [this page](https://developer.autelrobotics.com/doc/v1.5/mobile_sdk/en/20/1), the mobile shall be connected to the RC using a USB cable. is there a detailed description of how to connect? how is the USB connection configured on both sides? is it in USB debugging mode? USB tethering mode? 
is it possible to run it on the RC tablet directly?

Thanks

**Comment by AutelSDK** [comment]
crash problems have resolved, you can run it on the RC tablet directly

**Comment by planewave** [comment]
thank you for the update. I can run it on the RC tablet now. the up left of the app shows as `EVO_2` instead of `UNKNOWN`
However, most of the command in the demo app got no return, the log shows `the execution of this process has timed out`

also in DSP tab:  
`getRFDataList`: crashed
`getCurrentRFData`: error the commend failed
`setCurrentRFData`: error has not select a RF Hz

it is still not useable, please fix. 

Thank you again

**Comment by AutelSDK** [comment]
has resolved
