### ISSUE TITLE
How to know how far a waypoint action has been executed

### ISSUE THREAD

**Issue by masayuki-kobayashi1** [AutelSDK/AndroidAdvanceSample#28]
I created a waypoint mission according to the "Tutorial on Implementing a New Flight Path Mission" and started the mission. 
Is there any way to know if a waypoint action has been performed at any waypoint?
The waypointSequence in Evo2WaypointRealTimeInfoImpl  Class indicates which waypoints are flown to in the mission, but it is not possible to know how many waypoint actions have been executed in the past.

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
I'd appreciate if you could answer these questions.

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK
Any updates?

**Comment by AutelSDK** [comment]
MissionManager.getAutelWaypointMissionInfoParser().setIWaypointUploadStatusListener(wplist,new AutelMissionInterface.IWaypointUploadStatusListener() {
 }

**Comment by AutelSDK** [comment]
<img width="921" alt="企业微信截图_f8b6485a-f6f5-483b-898d-e2e6015bac8b" src="https://github.com/AutelSDK/AndroidAdvanceSample/assets/42387860/680a57c9-109c-449c-ae32-ae39a58d1395">

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
What we want to know is not how many waypoints are now, but how many waypoint actions have been executed so far.
