### ISSUE TITLE
Need to be provided description for each type of CameraAction

### ISSUE THREAD

**Issue by masayuki-kobayashi1** [AutelSDK/AndroidAdvanceSample#29]
@AutelSDK 
I am trying to add a camera action to Waypoint mission.
I think CameraActionJNI is the camera action, but I would like to know what each enum means.
CameraActionJNI is written in [here](https://developer.autelrobotics.com/doc/v1.5/mobile_sdk/en/50/6)

```
public enum CameraAction {
    NONE(10),
    TAKE_PHOTO(1),
    RECORD(2),
    TIMELAPSE(3),
    DISTANCE(4),
    DISTANCE_SCAN(5),
    STOP_RECORD(6),
    STOP_PHOTO(7),
    POINT_TAKE_PHOTO(11),
    POINT_RECORD(12),
    POINT_TIMELAPSE(13),
    POINT_NONE(20),
    UNKNOWN(-1);
}
```

```
public class CameraActionJNI {
     /** Action type */
    public int Action_Type;

     /** Pitch angle of the gimbal */
    public float Gimbal_Pitch;

     /** Roll angle of the gimbal */
    public float Gimbal_Roll;

     /** Yaw angle of the gimbal */
    public float Action_Yaw_Ref;

     /** Interval between periodic shoots (s) */
    public int Shoot_Time_Interval;

     /** Distance for fixed-distance photography (mm) */
    public float Shoot_Dis_Interval;

     /** Action execution time (s) */
    public int Action_Time;

     /** zoom factor */
    public int Zoom_Rate;

     /** Reserved */
    public int[] reserved;//2
}
```

And, If I want to perform multiple actions in any waypoint, how should I implement it?
For example, with a specific WP, I want the drone to turn the gimbal angle to 90°, take a picture, wait 3 seconds, then take another picture)
Please could you give me an example code?
Thank you.

**Comment by AutelSDK** [comment]
https://github.com/AutelSDK/MSDK2.0_MissionDemo  similar to this

**Comment by AutelSDK** [comment]
public enum CameraAction {
    /**
     * Waypoint Action - None
     **/
    NONE(10),
    /**
     * Waypoint Action - Take Photo
     **/
    TAKE_PHOTO(1),
    /**
     * Waypoint Action - Record Video
     **/
    RECORD(2),
    /**
     * Waypoint Action - Timelapse
     **/
    TIMELAPSE(3),
    /**
     * Waypoint Action - Fixed Distance Photo
     **/
    DISTANCE(4),
    /**
     * Waypoint Action - Fixed Distance Scanning Photo
     **/
    DISTANCE_SCAN(5),
    /**
     * Waypoint Action - Stop Recording
     **/
    STOP_RECORD(6),
    /**
     * Waypoint Action - Stop Taking Photos
     **/
    STOP_PHOTO(7),
    /**
     * Point Action - Take Photo
     **/
    POINT_TAKE_PHOTO(11),
    /**
     * Point Action - Record Video
     **/
    POINT_RECORD(12),
    /**
     * Point Action - Timelapse
     * May 10, 2022, Change value 3 -> 13 to distinguish between point actions and waypoint actions
     **/
    POINT_TIMELAPSE(13),
    /**
     * Point Action - None
     **/
    POINT_NONE(20),

    UNKNOWN(-1);
}

**Comment by AutelSDK** [comment]
![企业微信截图_16968156638809](https://github.com/AutelSDK/AndroidAdvanceSample/assets/42387860/fc024860-a365-43b3-b232-e19d96b0b565)
AirLineCreator this class

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
Can you give me some information as it is very difficult to know the difference on my own?
