### ISSUE TITLE
How can I make a waypoint shoot without making it stop moving?

### ISSUE THREAD

**Issue by masayuki-kobayashi1** [AutelSDK/AndroidAdvanceSample#30]
We would like to do a photo shoot at the waypoint mission.
When taking pictures on a waypoint mission, is it possible to set the camera to take pictures while moving?
As far as I have confirmed, the behavior is to stop hovering at each waypoint, take a picture, move to the next waypoint, stop hovering, and repeat.
I would like to have the camera move while shooting without stopping at waypoints.
Thanks.

**Comment by AutelSDK** [comment]
/
* Waypoint Action - Fixed Distance Photo
/
DISTANCE(4),
/

/
* Point Action - Timelapse
/
POINT_TIMELAPSE(13),

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
I think both DISTANCE and POINT_TIMELAPSE stay at the waypoint until the action is completed, am I wrong in my understanding?

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
Any updates?

**Comment by masayuki-kobayashi1** [comment]
@AutelSDK 
What are the rules for distance-based photo capture settings?
