### ISSUE TITLE
Is there any difference in the use of the SDK between the RTK model and the none model?

### ISSUE THREAD

**Issue by masayuki-kobayashi1** [AutelSDK/AndroidAdvanceSample#33]
I was able to run a waypoint mission using the SDK on [a regular model without RTK](https://shop.autelrobotics.com/collections/autel-evo-ii-series/products/evo-ii-dual-640t-rugged-bundle-v3).
With the same code, I was able to execute a waypoint mission on [the model with RTK](https://shop.autelrobotics.com/collections/autel-evo-ii-series/products/evo-ii-dual-640t-rtk-rugged-bundle-v3), but the aircraft did not move at all.
Are there any parameters that need to be taken into account for different models with the SDK?

**Comment by masayuki-kobayashi1** [comment]
I found this to be due to the different camera models between the two.

**Comment by AutelSDK** [comment]
Yes, it should not be related to whether there is RTK or not.
