### ISSUE TITLE
Update targetSdkVersion to 33

### ISSUE THREAD

**Issue by tuannguyenneo** [AutelSDK/AndroidAdvanceSample#9]
**Description:**
Currently, the targetSdkVersion in the Android app is set to 29. However, according to the requirements for app upload, the minimum required targetSdkVersion is 33.

**Steps to Reproduce:**

Open the build.gradle app level.

**Expected Behavior:**
To meet the app upload requirements, the targetSdkVersion needs to be updated to 33.

**Actual Behavior:**
The current targetSdkVersion in the Android app is set to 29, which does not fulfill the minimum requirement for app upload.
![image](https://github.com/AutelSDK/AndroidAdvanceSample/assets/122004255/cde252b0-2e52-4e94-b187-3fb160f7ef9b)

**Proposed Solution:**
Please update the targetSdkVersion in the Android app's configuration to 33 or higher to comply with the app store's upload requirements.

**Additional Information:**

Updating the targetSdkVersion to the latest available version is recommended for compatibility, performance, and security reasons.
Please consider the necessary compatibility adjustments or feature updates that may be required when updating the targetSdkVersion.
If there are any concerns or potential challenges related to updating the targetSdkVersion, please provide guidance or alternative solutions.

Commit ID: **_`8a32fb0c19de02159eadeb9f46acb50146996040`_**

Thank you for your attention to this matter. I look forward to your prompt resolution of this issue.

**Comment by starcheek** [comment]
Quick fix woudl be to add 
```    minSdk 23
        //noinspection ExpiredTargetSdkVersion
        targetSdk 29```

**Comment by tuannguyenneo** [comment]
@starcheek 

Please take a look at this ticket's purpose:
`Please update the targetSdkVersion in the Android app's configuration to 33 or higher to comply with the **app store's upload requirements.**`

This is [the document](https://developer.android.com/google/play/requirements/target-sdk) related this issue:
![image](https://github.com/AutelSDK/AndroidAdvanceSample/assets/122004255/2a17a3d4-5a64-4e30-b33f-f15c3faff3ce)

I think your idea to ignore a warning from the Android Studio and it's not a right solution.

Anw, thank you for your support.
